language: cpp
compiler:
  - gcc
env:
  matrix:
    - BUILD_ARCH=x86
    - BUILD_ARCH=x86_64
before_install:
  - sudo apt-get install -qq libc6-dev-i386 gcc-multilib g++-multilib
script:
  - ./build.sh
branches:
  only:
    - master
notifications:
  email:
    on_success: change
    on_failure: always
