--- 
branches: 
  only: 
  - master
language: cpp
compiler: 
- gcc
env: 
  matrix: 
  - BUILD_ARCH=x86
  - BUILD_ARCH=x86_64
  global: 
  - ARTIFACT_REPO=git@github.com:occ/jzmq-native-artifacts
  - secure: |-
      cgWJ7NauFYIvZqrmi4saQvmtCtU9fjeintTuL3SJzPGbIiYq3aDrCWVwxErk
      kuOX79+Jy3bQYmtybZL7ExjXgxC52+uMmCK+GK28I6Abw8INmNkRAgu1MpmI
      gbtFx52L49fObOFNHsHgLI+GGUXEeuSebPMS+ZqpcePhDd+ALAU=
  - secure: |-
      iP+CEOCg35XnF+/x1PcFBwsTYfaBIDgegw/YQGKLTLGAs35yM3ITWz/gXLrw
      OFJUZzZHz0qQAfKfEUPqVLRMCnFokOxzk6Z4savBidYOfj8ian4n4XMW5ScU
      51dJhVsRtttIog9HUxKuj9T/33OmY9/kRQwqzkuRzwM0PYlQpfM=
  - secure: |-
      hFz+b/bvKIp/btrzHMYxnwbWq0yj9Oztf7V41KF+TMJZUgfmOTRubPvHkvxO
      XmUr8f1KXB6jyHNxIjYGa15lr/kOCAVAAAjQRCTt5wCqqWUQ0SsuhI4JkQ89
      +2IDSfiU+PesUHaeAu3sDCHJPKaXlSKnbCzkCgu01rh2B7+7Zjg=
  - secure: |-
      pMiYOGP3CywmVcPEJJYNiDrxzpZTbhIfQrp18ajH5FDatT0lBFvdy02KzynL
      jApsX3Nb7sJ4HeiqetcszuDIn9l9jCnGYXkyxmrx4D/7rireDm1Oz95dv5+n
      sTyZhhDf9oFEwJ5PRRk+2Qte0Sus6wL0v9sTIcOCHIWnWz+TAjI=
  - secure: |-
      hRAVODZe7uYXTbzrppXEIGIXWgq/M8YqBU5bR2ZQpAzLKWWZMAqkAwcqsi4d
      MNhc9Di+BxG8W0YaK3lQjdDM0hHpc8kfJS13aTrq9PAL6u6iJ2ZUPQO3QFcg
      LLN2gHcXuhNMczUepjtgvpIudgznTPZLYitOZtvUNT080n47DNM=
  - secure: |-
      FPz78DZKZYSF/eBVcYQIxDImqbTxSs2MfOiv7jv7mmpArE+UdDmq/afDrYQV
      WGvOIwR+XWxRM8kTszqtjRz5yMDCHNsBIMPEM4xK7ILs4YRznl/H8WY6Mrsp
      HKuxp5As6V6ccWOr8XjED3K131qkQU3wmJ/LNTlu7WSmdXjHJXQ=
  - secure: |-
      LuON1kylK82bAr/pDxkXzT5fzmIZIkMCECHofXjGDf3IoJkWC/yFYGEOvf1K
      aVFY0VepTDtH6yf1vQF6UtQiRC8qkrRXl0Bxbj+ovAB/ozwmdcoVw+1RRzNA
      oRJ9VsARp0/Tf33Cy/OLs173uPNeBzNjnLb21CFvRZk3lVasLVw=
  - secure: |-
      oIgjPD6PEOa4cOdKfYeoDohGzTq4rq1gA2I7lo6DTYUcg56UugANnb2mCtVh
      BFK3+g1If5VC1+Ljq7o2OSvrAQmpUszjq0B/pt3xjtjvXitomTW2BqNpeCp5
      ylj0O4EiDr8RMQnjYLD9O1EvABuQ/xnTtT+DFYQi4pJH/BtBX0o=
  - secure: |-
      UytypFCaQ/trmlpi4zUM1a9C+pkMnE7lcELtdEkE6Fx8TpCEAnShjt9rfC4/
      Mj4ImNWGcnPFHGvF+aKFk0jkKtPU01nw5kQB2SMGLXqlR1xmw+pr2S3WkXU8
      IinQNBQHjWKAf6hCiOdt+ooKKYveqKKWwwvcbcNdSXuLL+a2dxU=
  - secure: |-
      m7mWlHWccyRJtFcYIp1s/1CiOrqzbbWtHid5eb/XL+Blunfh9ubQW3iHFVwv
      d5mQUFRhCEi5FSVhWOqNnfRhqVZVsyCy32tsEEZEhbonEcGHCiMbaLTyq3n9
      8jZyrYWl6hlH1gV6l9qDELGONqpqK+57F4dQ1p1aGWTeNr+JSbI=
  - secure: |-
      Cl9COB3glB7rqH/BUSI/JUp7w3T74Dx3NqbxW1PkrdqjJ90+FJgqtGbtuewV
      YSQNjveHNcEQedZudBbkuDLVJ+luh8E9nz0QmixVCDNRovM3P1BI0hpKmEyZ
      5KX2FXtxTYIjlVr/7Kajh5vCzLWXKgeZGbwSRcmjJhwiMG2m1xo=
  - secure: |-
      fU/a+6LjBpzKcq9oG89fwdnd+qQfGzA1nvuLkyyLGkqgadGfaDiR5lc9G7rj
      nJwCehtbar9i5y9y2EZN7CNw5flaBxA/U5UxS84OoqtX1DoCp/OKfA1Hh+K3
      UHK9UbhZTOa88I5oudOPcoNqjEENKnX1YrwY9K/0NznDix1W9K4=
  - secure: |-
      gAO5qM8ZUrPHCn46k2wLlIz+zHc/MTHMVJ4n2I7HvOON+eK11wDhOWJsax+1
      wzPl/nZ7KK8cPsjJr33oOqaCtYX6OLfWJ0mhgtLGbPCjlGgzSuGWahxN1IUf
      VGwsgxTlMQKo0ER7f7m77GsHxKU/9FEhxdPMj5yA4Jm01WCBkWI=
  - secure: |-
      pW8sMROLNV3mjHsknIWmnDEG7TMUoDL15H7x0XG9rHytRApowa0PhW6Btd1a
      aPf6qIV72nnBjjpgYuzEtRPM+IgyJsE+dxSKPSpX5VRKMUg0WBsl72B+tDGL
      xa7USMiJx9vh0nNNTm+C0NgqK2bdHvGTuTJ7pl65o45LrXEyoWw=
  - secure: |-
      fxgnttc/eNuHCCkkw3I8zED84Hg0E0HM6QQshiBwEY6QoTqJlXgorPKjzekg
      En93w26oX0Gob0QIJeFoXY0bLpLGPuqNoRDz7Wa0V2ikI8pwo/bGuWYjxcr0
      a6kEdh2FwgnwovhwJxNv58e0dqHildzJzcfiYulNtvlcWX/4BO0=
  - secure: |-
      WjoVTMv2e65LnFuJZ4HS6AD1ixcbX69nUkFHLGV4pb1g9bEoxyRzjMWVhRV7
      /vEH8Ghl6o8zh/rl5PzSIlQ1idURiIBXjY37tw3VG+L+TqWDIqKaFoXmCldr
      YRYoQfXnjwgM3ihYqGgaC0iAv9NJQt/Lg0tkM62rGgrGNsm/sNw=
  - secure: |-
      NXm/8yLIRHSWjlC84q4yLl9BwoHhiLrArkO7vXfInmj9Dq8f+7TGIyltI8No
      3v5CANkJc2fxbJdHm+XQuIL0KlS+uXvYo4DLCLGdupd4RsmkUG8mLHHYuPwu
      sRICE6kkw0H4qn4sLaeaV3gMrr61nCUQXeAU0CQ/+aYOXl/0WoU=
  - secure: |-
      OtcnL8nsUTWww8h328tqBkzPGUR36SdbL6yZi/pxR7OwbJfn3PW6IQ9Ou9Xz
      S0swe64JLYophKfqtRJpaxX4dc6kj3CXUXUMCGnXyi4uGYjmf5PlIVFFo/zu
      aL3EpC58epwQzdf56l0hF0xG2/AUAJCoRf7zZkuP6hQLFr1YwSA=
  - secure: |-
      gowokY795DcSLD1GTHkYzRrZIfY853Cb471XWCJYXeewBxUqaX4/fnCpCPXC
      adl/TBUGut3+MgMb9VlYPG7KjJM0AzMWLQE/ls4JHVBV3swAoh2FxUc/tB5G
      5a6kx6Ka5kDSpyKjoja2Xpn9wWASTDTGc9nROC4gjergbXv3QbA=
  - secure: |-
      C5SJxbbzSVBe6ODbl54etcMgcUUBD1cuxerstX37kFqfsi3wH447aBw8Lw4/
      2tzvjq70tZeaoRzsbQOqTrlSmEhEJ8U9xKmvz4MZ4aHoUEi/KROzNb48AfJB
      WO5JfCfqJIIFnC1ME6xuZDctBrCTY/BgpXXcmxH62FUACpDicPI=
  - secure: |-
      bH44lLt3De0b3LCjPbPQ4byQNJq7Ad/vSPBxhi9EJiKdPaAMBfB2DEnwonPp
      2QTlfFMRU2Z5hSURGsKc3bGJTi8f9ubv9eO0/BpfMNTVPXvYSAh17dRGpv6d
      gLIUc4GZ95Sx86UzkEtPPUbJkgRhEcexv5FJyfIPYxas/Ewn1YU=
  - secure: |-
      l/GBUsSb6Co9OfhWsIgi2O3V+bURskf9dVNAM6BdzFGP34L2pnWUUJoqAceF
      QKch/bRZHmfQC5R3B6a8RduYV1E8f+kHe56LMhU++eVXyCYl/koZFmR23WJo
      x2IGXT3tAb8LsI4ywqBtuk4J78NRFRRUzh1f52HuGt1Tpdgzf+k=
  - secure: |-
      UuXaI2YY59yTsR7Z8z3CGbVxTH8IrfObA98Ut3PDgPHX2GydxV54jl7kOKhi
      gVKmsejp5fRwHP3YQl46Kq2uTsB4FPwXG0lFBNPBz/i5iK+UOPE9bvdb0V4f
      ny0aMXpStKbEZ7901gLoodDsJY+vf75RjMYRYZNuykBe26xsz+0=
before_install: 
- sudo apt-get install -qq libc6-dev-i386 gcc-multilib g++-multilib
notifications: 
  email: 
    on_success: change
    on_failure: always
script: 
- ./build.sh
