language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get install -qq libc6-dev-i386
script:
  - ./build.sh
branches:
  only:
    - master
notifications:
  email:
    on_success: change
    on_failure: always
